name: CI for FastAPI Todo App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Verificar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3
       
      
      # 2. Configurar Docker en GitHub Actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      

      # 3. Construir la imagen de Docker
      - name: Build and tag Docker image
        run: |
          docker build -t fastapi-todo-app .


      # 5. Correr pruebas unitarias
      - name: Run tests
        run: |
          docker run --rm fastapi-todo-app pytest